spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_talk
    username: root
    password: 123456
  data:
    redis:
      host: 172.18.9.202
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
deepseek:
  api:
    base-url: https://api.deepseek.com
    chat-endpoint: /chat/completions
    api-key: sk-a3b25bf74d3b4853870c18a6acdf17c7
pagehelper:
  auto-runtime-dialect: true